# Определение базовых URL сервисов
services:
  notification: http://localhost:8087
  auth: http://localhost:8095
  frontend: http://localhost:8010
  profile: http://localhost:8090
  admin: http://localhost:8020
  minio: http://localhost:8030

# Конфигурация CORS: разрешённые источники берутся из свойств services
cors:
  allowed-origins:
    - ${services.notification}  # notification service
    - ${services.auth}          # auth service
    - ${services.frontend}      # frontend service
    - ${services.profile}       # profile service
    - ${services.admin}         # admin service
    - ${services.minio}         # minio service

# Определение URL эндпоинтов для различных операций
endpoints:
  notification:
    sendMail: ${services.notification}/api/notification/send
    publicSendMail: ${services.notification}/api/public-notification/send
  auth:
    resetRequest: ${services.auth}/api/auth/reset-password
    verificationRequest: ${services.auth}/api/auth/verify-email
  frontend:
    resetRequest: ${services.frontend}/reset-password
    login: ${services.frontend}/login
  profile:
    getAllProfiles: ${services.profile}/api/profile
    getUnverifiedProfiles: ${services.profile}/api/profile/unverified
    verifyProfile: ${services.profile}/api/profile/verify
    cancelValidation: ${services.profile}/api/profile/cancel-validation
  minio:
    uploadFile: ${services.minio}/api/file/upload
